# Generated by Django 5.1.5 on 2025-02-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0002_userregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='deptname',
        ),
    ]
