# Generated by Django 5.1.5 on 2025-02-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0003_rename_name_department_deptname'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='contact',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
