# Generated by Django 5.1.5 on 2025-02-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0004_staff_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
