# Generated by Django 5.1.5 on 2025-02-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0005_staff_password_staff_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='full_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='gender',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='phone_number',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='username',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
    ]
