# Generated by Django 5.1.5 on 2025-02-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0007_ngo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='updated_at',
        ),
    ]
