# Generated by Django 5.1.5 on 2025-02-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0008_remove_ngo_created_at_remove_ngo_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='ngo_name',
            field=models.CharField(max_length=255),
        ),
    ]
