# Generated by Django 5.1.5 on 2025-02-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0009_alter_ngo_email_alter_ngo_ngo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
