# Generated by Django 5.1.5 on 2025-02-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0013_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='Locationname',
        ),
    ]
