# Generated by Django 5.1.5 on 2025-02-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0014_rename_name_location_locationname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Locationname',
            new_name='name',
        ),
    ]
