# Generated by Django 5.1.5 on 2025-02-12 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0016_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('current_occupants', models.PositiveIntegerField(default=0)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floodmanager.amenities')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floodmanager.location')),
            ],
        ),
    ]
