# Generated by Django 5.1.5 on 2025-02-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0017_reliefcamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliefcamp',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
