# Generated by Django 5.1.5 on 2025-02-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0019_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='precipitation',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wind_speed',
        ),
    ]
