# Generated by Django 5.1.5 on 2025-02-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0021_rainfalllocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rainfalllocation',
            name='created_at',
        ),
    ]
