# Generated by Django 5.1.5 on 2025-02-12 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0022_remove_rainfalllocation_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallIntensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rainfall_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('rainfall_intensity', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floodmanager.rainfalllocation')),
            ],
        ),
    ]
