# Generated by Django 5.1.5 on 2025-02-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0028_rename_time_evacuationrecord_evacuationtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evacuationrecord',
            old_name='date',
            new_name='evacuationdate',
        ),
    ]
