# Generated by Django 5.1.5 on 2025-02-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0029_rename_date_evacuationrecord_evacuationdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistration',
        ),
        migrations.RenameField(
            model_name='evacuationrecord',
            old_name='evacuationdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='evacuationrecord',
            old_name='evacuationtime',
            new_name='time1',
        ),
    ]
