# Generated by Django 5.1.5 on 2025-02-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0030_delete_userregistration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evacuationrecord',
            old_name='date',
            new_name='evacuationdate',
        ),
        migrations.RenameField(
            model_name='evacuationrecord',
            old_name='time1',
            new_name='evacuationtime',
        ),
    ]
