# Generated by Django 5.1.5 on 2025-02-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0031_rename_date_evacuationrecord_evacuationdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Staffuserregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=9)),
                ('aadhaar_no', models.CharField(max_length=12)),
                ('landscape_level', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('house_no', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('members', models.ManyToManyField(blank=True, to='floodmanager.householdmember')),
            ],
        ),
    ]
