# Generated by Django 5.1.5 on 2025-02-17 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0032_householdmember_staffuserregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuserregistration',
            name='members',
        ),
        migrations.AddField(
            model_name='householdmember',
            name='familyid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='floodmanager.staffuserregistration'),
        ),
    ]
