# Generated by Django 5.1.5 on 2025-02-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0033_remove_staffuserregistration_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdmember',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staffuserregistration',
            name='aadhaar_no',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='staffuserregistration',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staffuserregistration',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staffuserregistration',
            name='house_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staffuserregistration',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staffuserregistration',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='staffuserregistration',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staffuserregistration',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staffuserregistration',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staffuserregistration',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='staffuserregistration',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
