# Generated by Django 5.1.5 on 2025-02-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0034_alter_householdmember_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuserregistration',
            name='Email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
