# Generated by Django 5.1.5 on 2025-02-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0036_remove_staffuserregistration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuserregistration',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
