# Generated by Django 5.1.5 on 2025-03-10 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0037_alter_staffuserregistration_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rainfallintensity',
            name='rainfall_id',
        ),
    ]
