# Generated by Django 5.1.5 on 2025-03-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0039_floodalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodalert',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
