# Generated by Django 5.1.5 on 2025-04-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0041_tempwaterlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempwaterlevel',
            name='iot_data_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
