# Generated by Django 5.1.5 on 2025-04-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0042_tempwaterlevel_iot_data_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRainfallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iot_data_id', models.IntegerField(default=0, unique=True)),
                ('rainfall_intensity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
