# Generated by Django 5.1.5 on 2025-04-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodmanager', '0043_temprainfalldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempWeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iot_data_id', models.IntegerField(default=0, unique=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
